apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: chartbrew
spec:
  ports:
    - port: 27018
      targetPort: 27017
  selector:
    app: mongodb
status:
  loadBalancer: {}
