apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: chartbrew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            failureThreshold: 10
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
              name: initdb-config
      restartPolicy: Always
      volumes:
        - name: mysql-claim0
          persistentVolumeClaim:
            claimName: mysql-claim0
        - name: initdb-config
          configMap:
            name: mysql-initdb-config
