apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: chartbrew
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis/redis-stack-server:latest
          name: redis
          ports:
            - containerPort: 6379
      restartPolicy: Always
status: {}
